### ISSUE TITLE
Found a way to make New York (Bold) Italic to work with MS Office

### ISSUE THREAD

**Issue by yell0wsuit** [NightFurySL2001/sfwin-office#2]
After several hours I found out how to make NY (Bold) Italic works in MS Office.
Since it's a Serif font, you have to make changes in `<panose>` section (I have to use FontForge as a reference). Its value, as taken from New York Regular:
```
<bFamilyType value="2"/>
<bSerifStyle value="2"/>
<bWeight value="5"/>
<bProportion value="2"/>
<bContrast value="6"/>
<bStrokeVariation value="4"/>
<bArmStyle value="0"/>
<bLetterForm value="0"/>
<bMidline value="0"/>
<bXHeight value="4"/>
```
Oh btw you might need to change the value in `macStyle` section so the italic style works in Office.

**Comment by NightFurySL2001** [comment]
@purifiedh2o Thanks a lot! I'll check it out. Any idea what happened?

`macStyle` is edited with the [php code](https://github.com/NightFurySL2001/sfwin-office/blob/master/lib/ttx_editing.php) line 12.

**Comment by yell0wsuit** [comment]
I think MS Office require strict Panose specifications for non sans-serif fonts, i.e. serif and monospace. I tried with trial-and-error so that's what I discovered.

**Comment by NightFurySL2001** [comment]
Fixing PANOSE table fixed the problem! I'll be uploading the file and code when I have time.

**Comment by NightFurySL2001** [comment]
@purifiedh2o test the fonts. Works like charm on my pc.
